using System.Globalization;
using System.Numerics;
using System.Text.Json;
using WardogsTool.Core.AntiAfk;
using WardogsTool.Core.Mortar;
using WardogsTool.Core.Parsing;

namespace WardogsTool.Core.Tests;

/// <summary>
/// Compares the C# port with outputs recorded from the unmodified Python tool
/// (Fixtures/python_reference.json, regenerated by tools/parity/gen_python_reference.py).
/// </summary>
public class PythonParityTests
{
    private static readonly JsonElement Reference = LoadReference();

    private static JsonElement LoadReference()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "python_reference.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.Clone();
    }

    private static double DecodeFloat(string s) => s switch
    {
        "nan" => double.NaN,
        "inf" => double.PositiveInfinity,
        "-inf" => double.NegativeInfinity,
        _ => KeepZeroSign(double.Parse(s, CultureInfo.InvariantCulture), s),
    };

    // .NET Framework's parsers return +0 for "-0.0"; Python's -0.0 must stay negative here, or the
    // sign checks below would pass vacuously.
    private static double KeepZeroSign(double value, string text) => value == 0 && text.StartsWith("-") ? -0.0 : value;

    private static double Num(JsonElement e) => KeepZeroSign(e.GetDouble(), e.GetRawText());

    [Fact]
    public void Mortar_matches_python_for_every_recorded_case()
    {
        var failures = new List<string>();
        var count = 0;
        var rangeTooLarge = 0;
        foreach (var c in Reference.GetProperty("mortar").EnumerateArray())
        {
            count++;
            var m = c.GetProperty("mortar");
            var t = c.GetProperty("target");
            var mortar = new MapPoint(Num(m[0]), Num(m[1]));
            var target = new MapPoint(Num(t[0]), Num(t[1]));
            if (BigInteger.Parse(c.GetProperty("range").GetRawText()) > long.MaxValue)
            {
                // Intended difference: Python prints the big integer; the port reports it.
                rangeTooLarge++;
                if (MortarCalculator.TrySolve(mortar, target, out _, out var e) || e != MortarCalculator.RangeTooLargeMessage)
                    failures.Add($"{mortar} -> {target}: expected the range-too-large message, got \"{e}\"");
                continue;
            }
            if (!MortarCalculator.TrySolve(mortar, target, out var s, out var error))
            {
                failures.Add($"{mortar} -> {target}: {error}");
                continue;
            }

            var bearing = c.GetProperty("bearing").GetDouble();
            var distance = c.GetProperty("distance").GetDouble();
            // Different libm builds may differ in the last bit of atan2/hypot; anything beyond
            // that is a real difference.
            if (Math.Abs(s.BearingDegrees - bearing) > 1e-9 || Math.Abs(s.DistanceMeters - distance) > 1e-9 * Math.Max(1, distance))
                failures.Add($"{mortar} -> {target}: exact {s.BearingDegrees:R}/{s.DistanceMeters:R} vs python {bearing:R}/{distance:R}");
            if (s.Direction != c.GetProperty("direction").GetInt32() || s.Range != c.GetProperty("range").GetInt64())
                failures.Add($"{mortar} -> {target}: {s.Direction}/{s.Range} vs python {c.GetProperty("direction")}/{c.GetProperty("range")}");
            Check(failures, c, "directionText", MortarText.Direction(s));
            Check(failures, c, "rangeText", MortarText.Range(s));
            Check(failures, c, "exactText", MortarText.Exact(s));
            Check(failures, c, "historyText", MortarText.HistoryEntry(target, s));
        }
        Assert.True(count > 4000, $"fixture has only {count} cases");
        Assert.Equal(1, rangeTooLarge);
        Assert.True(failures.Count == 0, $"{failures.Count} mismatches:\n" + string.Join("\n", failures.Take(20)));
    }

    private static void Check(List<string> failures, JsonElement c, string field, string actual)
    {
        var expected = c.GetProperty(field).GetString();
        if (expected != actual)
            failures.Add($"{field}: \"{actual}\" vs python \"{expected}\"");
    }

    [Fact]
    public void Coordinate_parsing_matches_python_parse_xy()
    {
        var failures = new List<string>();
        foreach (var c in Reference.GetProperty("parse").EnumerateArray())
        {
            var input = c.GetProperty("input").GetString()!;
            var ok = CoordinateParser.TryParse(input, out var p, out var error);
            if (c.GetProperty("ok").GetBoolean())
            {
                var x = DecodeFloat(c.GetProperty("x").GetString()!);
                var y = DecodeFloat(c.GetProperty("y").GetString()!);
                if (!ok || !p.X.Equals(x) || !p.Y.Equals(y) || DoublePolyfills.IsNegative(p.X) != DoublePolyfills.IsNegative(x))
                    failures.Add($"{Show(input)}: got ok={ok} ({p.X:R}, {p.Y:R}) {error}, python ({x:R}, {y:R})");
            }
            else
            {
                var expected = c.GetProperty("error").GetString();
                if (ok || error != expected)
                    failures.Add($"{Show(input)}: got ok={ok} \"{error}\", python \"{expected}\"");
            }
        }
        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    [Fact]
    public void Anti_afk_validation_matches_python_read_afk_settings()
    {
        // VkKeyScanW is a Windows call; use the virtual keys Python recorded for each key.
        var keys = new Dictionary<char, byte>();
        foreach (var c in Reference.GetProperty("antiAfk").EnumerateArray())
            if (c.GetProperty("ok").GetBoolean())
                keys[c.GetProperty("key").GetString()![0]] = (byte)c.GetProperty("vk").GetInt32();
        var keyboard = new FakeKeyboard(null, keys);

        var failures = new List<string>();
        var divergences = new List<string>();
        foreach (var c in Reference.GetProperty("antiAfk").EnumerateArray())
        {
            string F(string name) => c.GetProperty(name).GetString()!;
            BigInteger I(string name) => BigInteger.Parse(c.GetProperty(name).GetRawText());
            var ok = AntiAfkSettings.TryValidate(F("key"), F("count"), F("gap"), F("period"), keyboard, out var plan, out var error);
            var label = $"({Show(F("key"))}, {Show(F("count"))}, {Show(F("gap"))}, {Show(F("period"))})";

            // Intended differences: inputs Python's read_afk_settings accepts but its scheduler
            // then cannot handle (crash, or millions of after() calls). The port rejects them.
            string? expectedRejection = null;
            if (c.TryGetProperty("pythonSchedulerError", out _))
                expectedRejection = PythonNumber.TryParseFloat(F("period"), out var p, out _) && DoublePolyfills.IsFinite(p)
                    ? AntiAfkSettings.PeriodTooLargeMessage
                    : AntiAfkSettings.NonFinitePeriodMessage;
            else if (c.GetProperty("ok").GetBoolean() && I("periodMs") > AntiAfkSettings.MaxPeriodMs)
                expectedRejection = AntiAfkSettings.PeriodTooLargeMessage;
            else if (c.GetProperty("ok").GetBoolean() && I("countValue") > int.MaxValue)
                expectedRejection = AntiAfkSettings.CountTooLargeMessage;

            if (expectedRejection is not null)
            {
                divergences.Add(F("period"));
                if (ok || error != expectedRejection)
                    failures.Add($"{label}: expected \"{expectedRejection}\", got ok={ok} \"{error}\"");
                continue;
            }
            if (c.GetProperty("ok").GetBoolean())
            {
                var gap = I("gapValue");
                var expectedGap = gap <= long.MaxValue ? (long)gap : 0; // unused when count == 1
                if (!ok || plan!.VirtualKey != c.GetProperty("vk").GetInt32() || plan.Count != (int)I("countValue")
                    || plan.GapMs != expectedGap || plan.PeriodMs != (long)I("periodMs"))
                    failures.Add($"{label}: got ok={ok} {plan} \"{error}\"");
            }
            else if (ok || error != F("error"))
            {
                failures.Add($"{label}: got ok={ok} \"{error}\", python \"{F("error")}\"");
            }
        }
        // inf, nan, 1e308 (period overflows), 1e12 (beyond the scheduler), a count of 1e20.
        Assert.Equal(5, divergences.Count);
        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    private static string Show(string s) => JsonSerializer.Serialize(s);
}
