using System.Globalization;
using System.Text.Json;
using WardogsTool.Core.AntiAfk;
using WardogsTool.Core.Mortar;
using WardogsTool.Core.Parsing;

namespace WardogsTool.Core.Tests;

/// <summary>
/// Compares the C# port with outputs recorded from the unmodified Python tool
/// (Fixtures/python_reference.json, regenerated by tools/parity/gen_python_reference.py).
/// </summary>
public class PythonParityTests
{
    private static readonly JsonElement Reference = LoadReference();

    private static JsonElement LoadReference()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "python_reference.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.Clone();
    }

    private static double DecodeFloat(string s) => s switch
    {
        "nan" => double.NaN,
        "inf" => double.PositiveInfinity,
        "-inf" => double.NegativeInfinity,
        _ => double.Parse(s, CultureInfo.InvariantCulture),
    };

    [Fact]
    public void Mortar_matches_python_for_every_recorded_case()
    {
        var failures = new List<string>();
        var count = 0;
        foreach (var c in Reference.GetProperty("mortar").EnumerateArray())
        {
            count++;
            var m = c.GetProperty("mortar");
            var t = c.GetProperty("target");
            var mortar = new MapPoint(m[0].GetDouble(), m[1].GetDouble());
            var target = new MapPoint(t[0].GetDouble(), t[1].GetDouble());
            if (!MortarCalculator.TrySolve(mortar, target, out var s, out var error))
            {
                failures.Add($"{mortar} -> {target}: {error}");
                continue;
            }

            var bearing = c.GetProperty("bearing").GetDouble();
            var distance = c.GetProperty("distance").GetDouble();
            // Different libm builds may differ in the last bit of atan2/hypot; anything beyond
            // that is a real difference.
            if (Math.Abs(s.BearingDegrees - bearing) > 1e-9 || Math.Abs(s.DistanceMeters - distance) > 1e-9 * Math.Max(1, distance))
                failures.Add($"{mortar} -> {target}: exact {s.BearingDegrees:R}/{s.DistanceMeters:R} vs python {bearing:R}/{distance:R}");
            if (s.Direction != c.GetProperty("direction").GetInt32() || s.Range != c.GetProperty("range").GetInt64())
                failures.Add($"{mortar} -> {target}: {s.Direction}/{s.Range} vs python {c.GetProperty("direction")}/{c.GetProperty("range")}");
            Check(failures, c, "directionText", MortarText.Direction(s));
            Check(failures, c, "rangeText", MortarText.Range(s));
            Check(failures, c, "exactText", MortarText.Exact(s));
            Check(failures, c, "historyText", MortarText.HistoryEntry(target, s));
        }
        Assert.True(count > 4000, $"fixture has only {count} cases");
        Assert.True(failures.Count == 0, $"{failures.Count} mismatches:\n" + string.Join("\n", failures.Take(20)));
    }

    private static void Check(List<string> failures, JsonElement c, string field, string actual)
    {
        var expected = c.GetProperty(field).GetString();
        if (expected != actual)
            failures.Add($"{field}: \"{actual}\" vs python \"{expected}\"");
    }

    [Fact]
    public void Coordinate_parsing_matches_python_parse_xy()
    {
        var failures = new List<string>();
        foreach (var c in Reference.GetProperty("parse").EnumerateArray())
        {
            var input = c.GetProperty("input").GetString()!;
            var ok = CoordinateParser.TryParse(input, out var p, out var error);
            if (c.GetProperty("ok").GetBoolean())
            {
                var x = DecodeFloat(c.GetProperty("x").GetString()!);
                var y = DecodeFloat(c.GetProperty("y").GetString()!);
                if (!ok || !p.X.Equals(x) || !p.Y.Equals(y) || double.IsNegative(p.X) != double.IsNegative(x))
                    failures.Add($"{Show(input)}: got ok={ok} ({p.X:R}, {p.Y:R}) {error}, python ({x:R}, {y:R})");
            }
            else
            {
                var expected = c.GetProperty("error").GetString();
                if (ok || error != expected)
                    failures.Add($"{Show(input)}: got ok={ok} \"{error}\", python \"{expected}\"");
            }
        }
        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    [Fact]
    public void Anti_afk_validation_matches_python_read_afk_settings()
    {
        // VkKeyScanW is a Windows call; use the virtual keys Python recorded for each key.
        var keys = new Dictionary<char, byte>();
        foreach (var c in Reference.GetProperty("antiAfk").EnumerateArray())
            if (c.GetProperty("ok").GetBoolean())
                keys[c.GetProperty("key").GetString()![0]] = (byte)c.GetProperty("vk").GetInt32();
        var keyboard = new FakeKeyboard(null, keys);

        var failures = new List<string>();
        var divergences = 0;
        foreach (var c in Reference.GetProperty("antiAfk").EnumerateArray())
        {
            string F(string name) => c.GetProperty(name).GetString()!;
            var ok = AntiAfkSettings.TryValidate(F("key"), F("count"), F("gap"), F("period"), keyboard, out var plan, out var error);
            var label = $"({Show(F("key"))}, {Show(F("count"))}, {Show(F("gap"))}, {Show(F("period"))})";

            if (c.TryGetProperty("pythonSchedulerError", out _))
            {
                // Python accepts inf/nan here and then crashes in schedule_cycle. The port
                // rejects them up front — the one intended difference.
                divergences++;
                if (ok || error != AntiAfkSettings.NonFinitePeriodMessage)
                    failures.Add($"{label}: expected the non-finite rejection, got ok={ok} \"{error}\"");
                continue;
            }
            if (c.GetProperty("ok").GetBoolean())
            {
                if (!ok || plan!.VirtualKey != c.GetProperty("vk").GetInt32() || plan.Count != c.GetProperty("countValue").GetInt32()
                    || plan.GapMs != c.GetProperty("gapValue").GetInt64() || plan.PeriodMs != c.GetProperty("periodMs").GetInt64())
                    failures.Add($"{label}: got ok={ok} {plan} \"{error}\"");
            }
            else if (ok || error != F("error"))
            {
                failures.Add($"{label}: got ok={ok} \"{error}\", python \"{F("error")}\"");
            }
        }
        Assert.Equal(2, divergences);
        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    private static string Show(string s) => JsonSerializer.Serialize(s);
}
